### PR TITLE
signer: Expose digest algorithm from Signer

### LINKED ISSUE #4: RSA_SIGN_PSS_4096_SHA512 uses incorrect Hash
You can see the issue here: https://github.com/sethvargo/go-gcpkms/blob/d27de45772d4964f90de6bc3aa86b06056ae74d0/pkg/gcpkms/signer.go#L114
That hash algorithm should use SHA512.

This isn't super critical as `RSA_SIGN_PSS_4096_SHA512` is a very rarely used algorithm.

### PR DESCRIPTION
**Pull request by josephlr**
This change does three things:
  - Exposes a `Signer.DigestAlg()` method indicating which hash algorithm _must_ be used with this key.
    - This is useful when attempting to write code that works with a user-supplied signing key
    - We are careful to only use the [`crypto.Hash`](https://golang.org/pkg/crypto/#Hash) methods that don't require the hash implementation to be linked in.
  - `Signer.Sign()` now checks that the `digest` and `ops` fields are correct
    - This is useful as the [`crypto.Signer` API](https://golang.org/pkg/crypto/#Signer) was initially created to work with private keys that could work with multiple different hash algorithms. However, this model does not apply to KMS keys.
    - Passing in incorrect parameters now fails earlier (without sending an API request) with a better error message.
    - This is similar to what we did for [TPM-based keys](https://github.com/google/go-tpm-tools/blob/4f3f3b508c7f808aec7ddbbe3ca3e1aa8276b0d6/tpm2tools/signer.go#L46-L51) (which have similar restrictions).
  - Fixes #4, so that `RSA_SIGN_PSS_4096_SHA512` works correctly.
    - This was missed in https://github.com/sethvargo/go-gcpkms/commit/a0ed38b9df1f6624c3a6ff9a4d2447d8b7beaeec, as `kmspb.CryptoKeyVersion_RSA_SIGN_PSS_4096_SHA512` was not added to the SHA512 case.

Signed-off-by: Joe Richey <joerichey@google.com>

### CODE REVIEW

File: pkg/gcpkms/signer.go [hunk 1]
```diff
@@ -89,6 +93,11 @@ func (s *Signer) Public() crypto.PublicKey {
 	return s.publicKey
 }
 
+// DigestAlg returns the hash algorithm used for computing the digest.
+func (s *Signer) DigestAlg() crypto.Hash {
```
Comment (sethvargo) [inline pkg/gcpkms/signer.go]: s/Alg/Algorithm please

**Review by sethvargo — CHANGES_REQUESTED** [review]

File: pkg/gcpkms/signer.go (hunk 1 above)
Comment (josephlr) [reply pkg/gcpkms/signer.go]: Fixed, good call.

**Review by sethvargo — APPROVED** [review]
